"""chg2__arajesh_schma_for_submission_metadata

Revision ID: 1ef5537e7175
Revises: 21db3f972662
Create Date: 2025-04-19 18:02:59.907182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ef5537e7175'
down_revision: Union[str, None] = '21db3f972662'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SubmissionMetadata',
    sa.Column('submissionId', sa.UUID(), nullable=False),
    sa.Column('problemId', sa.Integer(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('language', sa.Enum('JAVA', 'PYTHON', 'C', 'CPP', name='language'), nullable=True),
    sa.Column('state', sa.Enum('RECEIVED', 'PROCESSING', 'COMPLETED', name='submissionstate'), nullable=True),
    sa.Column('statusCode', sa.Integer(), nullable=True),
    sa.Column('testsPassed', sa.Integer(), nullable=True),
    sa.Column('totalTests', sa.Integer(), nullable=True),
    sa.Column('executionTime', sa.Float(), nullable=True),
    sa.Column('memory', sa.Float(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('submissionId')
    )
    op.add_column('UserMetadata', sa.Column('password', sa.String(length=60), nullable=True))
    op.alter_column('UserMetadata', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('UserMetadata', 'problemssolved')
    op.drop_column('UserMetadata', 'created_at')
    op.drop_column('UserMetadata', 'rank')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserMetadata', sa.Column('rank', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('UserMetadata', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('UserMetadata', sa.Column('problemssolved', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.alter_column('UserMetadata', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('UserMetadata', 'password')
    op.drop_table('SubmissionMetadata')
    # ### end Alembic commands ###
