"""chg1__arajesh__Alter schma for problem metadata

Revision ID: 21db3f972662
Revises: 236dcefcff44
Create Date: 2025-03-30 13:01:28.389170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21db3f972662'
down_revision: Union[str, None] = '236dcefcff44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ProblemMetadata', sa.Column('tags', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.alter_column('ProblemMetadata', 'problemTitle',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ProblemMetadata', 'difficulty',
               existing_type=postgresql.ENUM('EASY', 'MEDIUM', 'HARD', name='difficulty'),
               nullable=False)
    op.drop_column('ProblemMetadata', 'description')
    op.drop_column('ProblemMetadata', 's3_path')
    op.drop_column('ProblemMetadata', 'Tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ProblemMetadata', sa.Column('Tags', postgresql.ARRAY(postgresql.ENUM('Board Game', 'Multi-Players', name='tag')), autoincrement=False, nullable=True))
    op.add_column('ProblemMetadata', sa.Column('s3_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('ProblemMetadata', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('ProblemMetadata', 'difficulty',
               existing_type=postgresql.ENUM('EASY', 'MEDIUM', 'HARD', name='difficulty'),
               nullable=True)
    op.alter_column('ProblemMetadata', 'problemTitle',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('ProblemMetadata', 'tags')
    # ### end Alembic commands ###
