"""chg2__arajesh_schma_for_submissionmetadata

Revision ID: 78491eaf4c59
Revises: f0f209736916
Create Date: 2025-06-01 10:09:02.004979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78491eaf4c59'
down_revision: Union[str, None] = 'f0f209736916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SubmissionMetadata',
    sa.Column('submissionId', sa.UUID(), nullable=False),
    sa.Column('problemId', sa.Integer(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('language', sa.Enum('JAVA', 'PYTHON', 'C', 'CPP', name='language'), nullable=True),
    sa.Column('state', sa.Enum('RECEIVED', 'PROCESSING', 'COMPLETED', name='submissionstate'), nullable=True),
    sa.Column('statusCode', sa.Integer(), nullable=True),
    sa.Column('testsPassed', sa.Integer(), nullable=True),
    sa.Column('totalTests', sa.Integer(), nullable=True),
    sa.Column('executionTime', sa.Float(), nullable=True),
    sa.Column('memory', sa.Float(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('submissionId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SubmissionMetadata')
    # ### end Alembic commands ###
