
      name: Deploy to AWS

      on:
        push:
          branches:
            - code_dockerisation_for_deployment
      permissions:
        id-token: write
        contents: read

      env:
        AWS_REGION: us-west-2
        ECR_REPOSITORY: lldfy-app
        ECS_CLUSTER: lldfyai_cluster
        ECS_SERVICE: lldfyManager
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

      jobs:
        deploy:
          runs-on: ubuntu-latest
          steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                aws-region: ${{ env.AWS_REGION }}

            - name: Login to ECR
              id: ecr-login
              run: |
               aws ecr get-login-password --region ${{ env.AWS_REGION }} | \
               docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

            - name: Build and push Docker image
              run: |
                docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest .
                docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest

            - name: Update task definition
              run: |
                # Get the current task definition
                TASK_DEFINITION=$(aws ecs describe-task-definition \
                  --task-definition ${{ env.ECS_SERVICE }} \
                  --region ${{ env.AWS_REGION }})
            
            # Update the image tag to "latest"
                UPDATED_TASK_DEFINITION=$(echo $TASK_DEFINITION | \
                  jq --arg IMAGE "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest" \
                  '.taskDefinition | .containerDefinitions[0].image = $IMAGE | del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)')
            
            # Register the updated task definition
               aws ecs register-task-definition \
                --family ${{ env.ECS_SERVICE }} \
                --cli-input-json "$UPDATED_TASK_DEFINITION" \
                --region ${{ env.AWS_REGION }}

            - name: Update ECS service
              run: |
                aws ecs update-service \
                --cluster ${{ env.ECS_CLUSTER }} \
                --service ${{ env.ECS_SERVICE }} \
                --task-definition ${{ env.ECS_SERVICE }} \
                --force-new-deployment \
                --region ${{ env.AWS_REGION }}